### ISSUE TITLE
Broken links for reference pages (404)

### ISSUE THREAD

**Issue by MitchMcQuinn** [Official-MoonDao/documentation#11]
Pages published in the "reference" section are inaccessible on the front end since we switched to Quartz.
How can we publish pages without adding them to the top-level navigation in this new setup?

**Comment by philiplinden** [comment]
Example: https://docs.moondao.com/Roles links to https://docs.moondao.com/@Delegate

**Comment by philiplinden** [comment]
[Roles](obsidian://open?vault=moondao-vault&file=MoonDAO%2Fdocs%2FRoles) lives at `MoonDAO/docs/Roles.md` and links to [@Delegate](obsidian://open?vault=moondao-vault&file=MoonDAO%2Freference%2FGlossary%2F%40Delegate) at `MoonDAO/reference/Glossary/@Delegate.md`.

When we [build the documentation](https://github.com/Official-MoonDao/moondao-vault/blob/main/.github/workflows/build-and-deploy.yaml) we declare `MoonDAO/docs` as the site's root directory.

Two things to look into:
1. Does Quartz allow links that go "up and around" to locations outside of the site directory? If not, we need to move the `MoonDAO/reference/Glossary` under `MoonDAO/docs`.
2. Does Quartz allow pages to be included in the site but not displayed in navigation? If not, we have to live with `Glossary` being somewhere in the main nav tree.

**Comment by philiplinden** [comment]
The answer to (2) is **yes**: https://quartz.jzhao.xyz/features/explorer#remove-list-of-elements-filter

**Comment by philiplinden** [comment]
Looks like the answer to (1) is **no**: https://github.com/jackyzha0/quartz/blob/097abc3cda0d9a6f3cfedfa3c6351648efd8d6b8/quartz/plugins/transformers/links.ts#L52
