### ISSUE TITLE
Page metadata cards show incorrect text/images

### ISSUE THREAD

**Issue by philiplinden** [Official-MoonDao/documentation#9]
![image](https://github.com/Official-MoonDao/moondao-vault/assets/45497023/b158c7df-65f7-4228-8bc3-6f73dedf1bfd)

1. The card shows the incorrect image. Instead of the Quartz 4 logo, it should show the MoonDAO logo.
2. The card description contains the same line of text repeated three times. It should instead show the text in the note's metadata `description` field or the contents of the note. No text should repeat (unless it is showing the note contents verbatim).

**Comment by philiplinden** [comment]
In general, the card sources its information from tags like
```html
<meta property="og:title" content="Site Title" />
<meta property="og:type" content="website" />
<meta property="og:url" content="http://my.site.com" />
<meta property="og:image" content="http://my.site.com/images/thumb.png" />
<meta property="og:description" content="Site description" />
<meta name="theme-color" content="#FF0000">

<!-- Include this to make the og:image larger -->
<meta name="twitter:card" content="summary_large_image">
```
([source](https://stackoverflow.com/a/54266944)

I'm not sure what metadata we should be using but here's a complete list of what's available in html5: https://gist.github.com/lancejpollard/1978404

**Comment by philiplinden** [comment]
Trying to figure out where quartz sets up the metadata.

Looks like [`description.ts`](https://github.com/jackyzha0/quartz/blob/v4/quartz/plugins/transformers/description.ts) builds the text blob that we're having trouble with.

Looks like [`frontmatter.ts`](https://github.com/jackyzha0/quartz/blob/v4/quartz/plugins/transformers/frontmatter.ts) parses the Obsidian-style yaml frontmatter, including `description`. So yes, we can explicitly set a description to use instead of trying to infer it from the note's content. Confirmed to be true from the docs https://quartz.jzhao.xyz/plugins/Description

There's also [`ContentMeta.tsx`](https://github.com/jackyzha0/quartz/blob/v4/quartz/components/ContentMeta.tsx) but I don't really understand if it's affecting the card in this case, or if it's like a component to display "other optional data on the page" rather than true HTML capital "M" Metadata.

**Comment by philiplinden** [comment]
From this PR https://github.com/jackyzha0/quartz/pull/919 it looks like HTML metas are set in `head.tsx`.

Also inferring from https://github.com/jackyzha0/quartz/blob/b30a200bd4ddc64f4fd3d2124fcda0b354847073/quartz.layout.ts#L18-L23 `ContentMeta.tsx` _does_ build the HTML metadata, but I guess we need to be editing the head.tsx file?

Bingo. https://github.com/jackyzha0/quartz/blob/b30a200bd4ddc64f4fd3d2124fcda0b354847073/quartz/components/Head.tsx#L8-L18

Side note: replacing `quartz/static/icon.png` and `quartz/static/og-image.png` with MoonDAO icons will fix the first problem identified in the OP.

**Comment by philiplinden** [comment]
Welp, inspecting the page source something is definitely busted...

```html
<html lang="en"><head><title>Introduction</title><meta charset="utf-8"/><link rel="preconnect" href="https://fonts.googleapis.com/"/><link rel="preconnect" href="https://fonts.gstatic.com/"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<meta property="og:title" content="Introduction"/>
<meta property="og:description" content="MoonDAO is going to the moon. MoonDAO is going to the moon. MoonDAO is going to the moon. MoonDAO is going to the moon. MoonDAO is going to the moon. MoonDAO is going to the moon."/>
<meta property="og:image" content="https://docs.moondao.com/static/og-image.png"/>
<meta property="og:width" content="1200"/>
<meta property="og:height" content="675"/><link rel="icon" href="[./static/icon.png](https://docs.moondao.com/static/icon.png)"/>
<meta name="description" content="MoonDAO is going to the moon. MoonDAO is going to the moon. MoonDAO is going to the moon. MoonDAO is going to the moon. MoonDAO is going to the moon. MoonDAO is going to the moon."/>
```

**Comment by philiplinden** [comment]
#10 proved that this is a bug in quartz upstream, or at least something wrong with `Head.tsx`.

**Comment by philiplinden** [comment]
Opened an upstream ticket here: https://github.com/jackyzha0/quartz/issues/980

**Comment by saberzero1** [comment]
https://github.com/jackyzha0/quartz/pull/981
